### PR TITLE
added $length to $mapped

### PR DESCRIPTION
**Pull request by serkandurusoy**
I often end up requiring the length of an array along with its index information (e.g. *item 1/7*), hence this pull request.

### CODE REVIEW

**Comment by raix** [comment]
Thanks @serkandurusoy

**Comment by serkandurusoy** [comment]
You're welcome. I see that you've given me push rights to this repo. Thanks, that's a first for me :)

What's your policy with updates, PR's etc?

**Comment by raix** [comment]
there should always be a pr/branch pr. feature/issue and a review/discussion of it - we have to add tests in and make sure they pass.

**Comment by serkandurusoy** [comment]
Oh, ok thanks. Then I guess [a fix I committed](https://github.com/raix/Meteor-handlebar-helpers/commit/aef581eb3073fac0e5bd7fbe0bddf907e5f101db) a couple of hours ago violates this policy!

**Comment by raix** [comment]
thats a quick fix - those can be applied abit faster (should still have tests in place though) :)

**Comment by serkandurusoy** [comment]
Got it!

What about releases? Although there are some updates, the last release landed on atmosphere 9 months ago :)

Do you have a roadmap for a new release?

**Comment by raix** [comment]
really 9months? would be nice to have autopublish on the master branch

**Comment by serkandurusoy** [comment]
I think that's what you should be doing as the repository owner. In case I get dark with the credentials ;)

**Comment by raix** [comment]
@serkandurusoy tried adding you is "serkandurusoy" your meteor.com username?

**Comment by serkandurusoy** [comment]
Yes, that's me!

**Comment by raix** [comment]
added

**Comment by serkandurusoy** [comment]
Great, thanks. Now I need to brush up on my autopublish skills so that I don't mess with anything.

**Pull request merged**
